### ISSUE TITLE
How to obtain row id, when button pressed ?

### ISSUE THREAD

**Issue by jbrodriguez** [yzsolo/react-native-swipe-left#2]
Currently, it's using a TouchableHighlights onPress signature.

How do I know for which row the button was pressed ?

**Comment by yzsolo** [comment]
@jbrodriguez  the ListView has a renderRow method, you can add the rowid as a props attribute to use in the swipe-left component.

**Comment by jbrodriguez** [comment]
Closing this since you merged the PR :)
Will you push the change to npm ?

**Comment by yzsolo** [comment]
@jbrodriguez a few minutes later，thank you for your PR :)
